# 查询oobj_guid的sql
oobj_guid = select oobj_guid from oobtable where obj_id = (SELECT OBJ_ID FROM OBJ WHERE OBJ_ENGNAME = :oobj_engname)

dst_field = select dst from as_table where as_rule= :as_rule and oobj_id = :oobj_guid

dst_field_id = select oof_id,oof_guid from pltfield where guid = :dst_field

[as_rule]
ShenFenZhengInfo = _身份证信息回填